# Statistics Sheet 3 Xinyi Zhang

In [10]:
import pandas_datareader as pd_data
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import scipy.stats as stats
import math
import statsmodels.api as sm
import scipy as sp

In [2]:
start_date = '2018-01-01'
end_date = '2018-12-31'
GS = pd_data.DataReader('GS','yahoo',start_date,end_date)
SPY = pd_data.DataReader('SPY', 'yahoo',start_date,end_date)
DIA = pd_data.DataReader('DIA', 'yahoo',start_date,end_date)
WMT = pd_data.DataReader('WMT', 'yahoo',start_date,end_date)
EURUSD = pd_data.DataReader('EURUSD=X', 'yahoo',start_date,end_date)
GBPUSD = pd_data.DataReader('GBPUSD=X', 'yahoo',start_date,end_date)

In [8]:
names = ['GS','SPY','DIA','WMT','EURUSD','GBPUSD']
fullList = myList = [GS['Adj Close'],SPY['Adj Close'],DIA['Adj Close'],WMT['Adj Close'],EURUSD['Adj Close'],GBPUSD['Adj Close']]
myDict = dict(zip(names, myList))
df = pd.DataFrame({ key:pd.Series(value) for key, value in myDict.items()})
df.head()

                    GS         SPY         DIA        WMT    EURUSD    GBPUSD
Date
2018-01-01         NaN         NaN         NaN        NaN  1.200495  1.351607
2018-01-02  232.547531  247.899780  224.689682  90.314171  1.201158  1.351132
2018-01-03  230.382782  249.467758  225.532166  91.101990  1.206345  1.359619
2018-01-04  233.602631  250.519318  227.026917  91.184425  1.201043  1.351132
2018-01-05  232.411118  252.188751  228.947586  91.724892  1.206884  1.355289

In [9]:
df_logret = np.log(allData).diff().dropna()
df_logret.head()

                  GS       SPY       DIA       WMT    EURUSD    GBPUSD
Date
2018-01-03 -0.009352  0.006305  0.003743  0.008685  0.004309  0.006262
2018-01-04  0.013879  0.004206  0.006606  0.000904 -0.004406 -0.006262
2018-01-05 -0.005114  0.006642  0.008425  0.005910  0.004852  0.003072
2018-01-08 -0.014626  0.001827 -0.000515  0.014673 -0.002603  0.001696
2018-01-09  0.008423  0.002261  0.004858 -0.012079 -0.005582 -0.000339

In [11]:
X = df_logret[['SPY','DIA','WMT','EURUSD','GBPUSD']]
X = sm.add_constant(X)
Y = df_logret['GS']

model_logret = sm.OLS(Y,X).fit()
y_fitted_logret = model_logret.predict(X)

model_logret.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     GS   R-squared:                       0.640
Model:                            OLS   Adj. R-squared:                  0.629
Method:                 Least Squares   F-statistic:                     62.50
Date:                Mon, 21 Nov 2022   Prob (F-statistic):           3.15e-37
Time:                        14:58:30   Log-Likelihood:                 574.81
No. Observations:                 182   AIC:                            -1138.
Df Residuals:                     176   BIC:                            -1118.
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0015      0.001     -1.903      0.059      -0.003    5.48e-05
SPY            0.2905      0.310      0.937      0.350      -0.321       0.902
DIA            0.9622      0.304      3.167      0.002       0.363       1.562
WMT           -0.1217      0.070     -1.730      0.085      -0.260       0.017
EURUSD        -0.1739      0.236     -0.738      0.462      -0.639       0.291
GBPUSD         0.3587      0.205      1.747      0.082      -0.047       0.764
==============================================================================
Omnibus:                       22.348   Durbin-Watson:                   1.875
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               72.702
Skew:                          -0.378   Prob(JB):                     1.63e-16
Kurtosis:                       6.003   Cond. No.                         555.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""